### ISSUE TITLE
Add more support for legacy color codes to prevent chat limit being reached using MiniMessage tags

### ISSUE THREAD

**Issue by Taahh** [plexusorg/Plex#72]

**Comment by VideoGameSmash12** [comment]
Just have it detect whether or not chat color codes are being used and then process them as components with Adventure's LegacyComponentSerializer instead of trying to over-engineer the system by trying to process everything as MiniMessage and then having to go through the effort of trying to replace legacy color codes with MiniMessage.

**Comment by Telesphoreo** [comment]
Added in https://github.com/plexusorg/Plex/commit/fbd36161d4f307a7440f89d42adca4766d5a1f59
